import { MissionActiveResponse } from 'types/mission';

export const mockActiveMissions: MissionActiveResponse = {
  missions: [
    // ===== DAILY / STEP =====
    {
      missionCheckId: 1,
      missionId: 1,
      title: '산책의 시작',
      category: 'STEP',
      periodType: 'DAILY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-01',
      goalValue: 3000,
      progressValue: 3000,
      isCompleted: false,
      completedAt: null,
    },
    {
      missionCheckId: 2,
      missionId: 2,
      title: '가벼운 발걸음',
      category: 'STEP',
      periodType: 'DAILY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-01',
      goalValue: 5000,
      progressValue: 0,
      isCompleted: false,
      completedAt: null,
    },
    {
      missionCheckId: 3,
      missionId: 3,
      title: '오늘도 건강하게',
      category: 'STEP',
      periodType: 'DAILY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-01',
      goalValue: 7000,
      progressValue: 0,
      isCompleted: false,
      completedAt: null,
    },
    {
      missionCheckId: 4,
      missionId: 4,
      title: '파워 워킹',
      category: 'STEP',
      periodType: 'DAILY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-01',
      goalValue: 10000,
      progressValue: 0,
      isCompleted: false,
      completedAt: null,
    },

    // ===== WEEKLY / STEP =====
    {
      missionCheckId: 5,
      missionId: 5,
      title: '주간 산책 루틴',
      category: 'STEP',
      periodType: 'WEEKLY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-07',
      goalValue: 35000,
      progressValue: 0,
      isCompleted: false,
      completedAt: null,
    },
    {
      missionCheckId: 6,
      missionId: 6,
      title: '활동적인 한 주',
      category: 'STEP',
      periodType: 'WEEKLY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-07',
      goalValue: 50000,
      progressValue: 0,
      isCompleted: false,
      completedAt: null,
    },
    {
      missionCheckId: 7,
      missionId: 7,
      title: '걷기 챌린저',
      category: 'STEP',
      periodType: 'WEEKLY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-07',
      goalValue: 70000,
      progressValue: 0,
      isCompleted: false,
      completedAt: null,
    },

    // ===== MONTHLY / STEP =====
    {
      missionCheckId: 8,
      missionId: 8,
      title: '한 달 걷기 습관',
      category: 'STEP',
      periodType: 'MONTHLY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-28',
      goalValue: 150000,
      progressValue: 0,
      isCompleted: false,
      completedAt: null,
    },
    {
      missionCheckId: 9,
      missionId: 9,
      title: '걷기 마스터',
      category: 'STEP',
      periodType: 'MONTHLY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-28',
      goalValue: 300000,
      progressValue: 0,
      isCompleted: false,
      completedAt: null,
    },

    // ===== DAILY / MEAL =====
    {
      missionCheckId: 10,
      missionId: 10,
      title: '첫 끼 기록',
      category: 'MEAL',
      periodType: 'DAILY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-01',
      goalValue: 1,
      progressValue: 0,
      isCompleted: false,
      completedAt: null,
    },
    {
      missionCheckId: 11,
      missionId: 11,
      title: '균형 잡힌 전심',
      category: 'MEAL',
      periodType: 'DAILY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-01',
      goalValue: 1,
      progressValue: 0,
      isCompleted: false,
      completedAt: null,
    },
    {
      missionCheckId: 12,
      missionId: 12,
      title: '건강한 마무리',
      category: 'MEAL',
      periodType: 'DAILY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-01',
      goalValue: 1,
      progressValue: 0,
      isCompleted: false,
      completedAt: null,
    },
    {
      missionCheckId: 13,
      missionId: 13,
      title: '완벽한 하루',
      category: 'MEAL',
      periodType: 'DAILY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-01',
      goalValue: 3,
      progressValue: 0,
      isCompleted: false,
      completedAt: null,
    },

    // ===== WEEKLY / MEAL =====
    {
      missionCheckId: 14,
      missionId: 14,
      title: '주간 식단 루틴',
      category: 'MEAL',
      periodType: 'WEEKLY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-07',
      goalValue: 5,
      progressValue: 0,
      isCompleted: false,
      completedAt: null,
    },
    {
      missionCheckId: 15,
      missionId: 15,
      title: '꾸준한 기록',
      category: 'MEAL',
      periodType: 'WEEKLY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-07',
      goalValue: 7,
      progressValue: 0,
      isCompleted: false,
      completedAt: null,
    },
    {
      missionCheckId: 16,
      missionId: 16,
      title: '한 달 식습관 챌린지',
      category: 'MEAL',
      periodType: 'MONTHLY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-28',
      goalValue: 20,
      progressValue: 0,
      isCompleted: false,
      completedAt: null,
    },
    {
      missionCheckId: 17,
      missionId: 17,
      title: '식단 마스터',
      category: 'MEAL',
      periodType: 'MONTHLY',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-28',
      goalValue: 30,
      progressValue: 0,
      isCompleted: false,
      completedAt: null,
    },
  ],
};
