import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3F4F6',
  },
  contentContainer: {
    padding: 20,
    paddingBottom: 40,
  },
  topSection: {
    marginBottom: 12,
  },
  monthHeaderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  header: {
    fontFamily: 'JUA',
    fontSize: 24,
    color: '#1F2937',
    textAlign: 'center',
    flex: 1,
  },
  arrowButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  arrowText: {
    fontSize: 20,
    color: '#4B5563',
    fontFamily: 'JUA',
  },
  subHeaderText: {
    fontFamily: 'GowunDodum',
    fontSize: 14,
    color: '#6B7280',
    marginTop: 4,
  },
  ctaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
  },
  ctaPrimary: {
    backgroundColor: '#111827',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginRight: 10,
  },
  ctaPrimaryText: {
    fontFamily: 'GowunDodum',
    fontSize: 13,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  ctaGhost: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
  },
  ctaGhostText: {
    fontFamily: 'GowunDodum',
    fontSize: 12,
    color: '#4B5563',
    fontWeight: '600',
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginTop: 14,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  summaryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  summaryTitle: {
    fontFamily: 'JUA',
    fontSize: 18,
    color: '#111827',
  },
  summaryDateText: {
    fontFamily: 'GowunDodum',
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 2,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  badgeSuccess: {
    backgroundColor: '#DCFCE7',
  },
  badgeProgress: {
    backgroundColor: '#E0E7FF',
  },
  badgeMuted: {
    backgroundColor: '#F3F4F6',
  },
  badgeText: {
    fontFamily: 'GowunDodum',
    fontSize: 11,
    color: '#111827',
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  summaryItem: {
    flex: 1,
    alignItems: 'center',
  },
  summaryLabel: {
    fontFamily: 'GowunDodum',
    fontSize: 12,
    color: '#6B7280',
  },
  summaryValue: {
    fontFamily: 'JUA',
    fontSize: 20,
    color: '#111827',
    marginTop: 6,
  },
  summaryUnit: {
    fontFamily: 'GowunDodum',
    fontSize: 11,
    color: '#9CA3AF',
    marginTop: 2,
  },
  summaryDivider: {
    width: 1,
    height: 46,
    backgroundColor: '#E5E7EB',
  },
  sectionHeader: {
    marginTop: 16,
    marginBottom: 8,
  },
  sectionTitle: {
    fontFamily: 'JUA',
    fontSize: 18,
    color: '#1F2937',
  },
  itemContainer: {
    padding: 14,
    marginVertical: 6,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  dateText: {
    fontFamily: 'JUA',
    fontSize: 14,
    color: '#111827',
    marginBottom: 2,
  },
  timeText: {
    fontFamily: 'GowunDodum',
    fontSize: 12,
    color: '#6B7280',
    marginRight: 20,
  },
  distanceText: {
    fontFamily: 'JUA',
    fontSize: 16,
    color: '#F97316',
    marginLeft: 'auto',
  },
  detailLink: {
    fontSize: 20,
    color: '#9CA3AF',
    fontWeight: 'bold',
    marginLeft: 10,
    fontFamily: 'JUA',
  },
  indexText: {
    fontSize: 18,
    fontWeight: 'bold',
    marginRight: 15,
    fontFamily: 'JUA',
  },
  chartCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#FDE68A',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  chartMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  chartMetaItem: {
    flex: 1,
  },
  chartMetaDivider: {
    width: 1,
    height: 24,
    backgroundColor: '#FDE68A',
    marginHorizontal: 10,
  },
  chartMetaLabel: {
    fontFamily: 'GowunDodum',
    fontSize: 11,
    color: '#9CA3AF',
    marginBottom: 2,
  },
  chartMetaValue: {
    fontFamily: 'JUA',
    fontSize: 15,
    color: '#111827',
  },
  chartMetaUnit: {
    fontFamily: 'GowunDodum',
    fontSize: 10,
    color: '#9CA3AF',
  },
  chartRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
  },
  chartUnitColumn: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  chartUnitText: {
    fontFamily: 'GowunDodum',
    fontSize: 11,
    color: '#9CA3AF',
  },
  lineChartStyle: {
    borderRadius: 12,
    marginTop: 12,
    alignSelf: 'center',
  },
  loadingIndicator: {
    marginTop: 20,
  },
  emptyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  emptyCardTitle: {
    fontFamily: 'JUA',
    fontSize: 16,
    color: '#111827',
    marginBottom: 6,
  },
  emptyCardText: {
    fontFamily: 'GowunDodum',
    fontSize: 12,
    color: '#6B7280',
  },
  chartEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
  },
  chartEmptyText: {
    fontFamily: 'GowunDodum',
    fontSize: 12,
    color: '#9CA3AF',
  },
});
