import { StyleSheet } from 'react-native';
import { SCREEN_HEIGHT } from './dimensions';
import { Colors, Fonts, Typography, Spacing, Radius } from './theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: Spacing.xxl,
    paddingTop: SCREEN_HEIGHT * 0.04,
    backgroundColor: Colors.background,
  },
  title: {
    fontSize: Typography.h2,
    fontWeight: '800',
    textAlign: 'center',
    fontFamily: Fonts.JUA,
    marginBottom: Spacing.sm,
    color: Colors.textPrimary,
  },
  subtitle: {
    fontSize: Typography.body,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: Spacing.xl,
    fontFamily: Fonts.JUA,
    color: Colors.textPrimary,
  },
  list: {
    flex: 1,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.textPrimary,
    marginBottom: Spacing.sm,
    marginTop: Spacing.xs,
    fontFamily: Fonts.JUA,
  },
  permissionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.background,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    padding: 14,
    marginBottom: Spacing.sm,
    position: 'relative',
  },
  permissionIcon: {
    fontSize: 28,
    marginRight: 14,
    color: Colors.background,
  },
  permissionText: {
    flex: 1,
  },
  permissionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: Spacing.xs,
  },
  permissionTitle: {
    fontSize: 15,
    fontWeight: '700',
    fontFamily: Fonts.JUA,
    color: Colors.textPrimary,
  },
  requiredBadge: {
    position: 'absolute',
    top: 16,
    right: 16,
    backgroundColor: '#FF6347',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: Spacing.xxs,
  },
  optionalBadge: {
    position: 'absolute',
    top: 16,
    right: 16,
    backgroundColor: Colors.info,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: Spacing.xxs,
  },
  optionalBadgeText: {
    color: Colors.surface,
    fontSize: 11,
    fontFamily: Fonts.Roboto_VariableFont,
  },
  requiredBadgeText: {
    color: Colors.surface,
    fontSize: 11,
    fontFamily: Fonts.Roboto_VariableFont,
  },
  permissionDescription: {
    fontSize: Typography.caption,
    color: Colors.textSecondary,
    fontFamily: Fonts.Roboto_VariableFont,
    lineHeight: 18,
  },
  buttonContainer: {
    paddingTop: Spacing.md,
    paddingBottom: Spacing.lg,
    gap: Spacing.sm,
  },
  buttonInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  checkIcon: {
    color: Colors.surface,
    fontSize: Typography.body,
    fontFamily: Fonts.Roboto_VariableFont,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  checkIconOptional: {
    color: '#FF6347',
    fontSize: Typography.body,
    fontFamily: Fonts.Roboto_VariableFont,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  requiredButton: {
    backgroundColor: '#FF6347',
    height: 52,
    borderRadius: Radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  requiredButtonText: {
    color: Colors.surface,
    fontSize: Typography.body,
    fontFamily: Fonts.JUA,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  optionalButton: {
    backgroundColor: Colors.surface,
    height: 52,
    borderRadius: Radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FF6347',
  },
  optionalButtonText: {
    color: '#FF6347',
    fontSize: Typography.body,
    fontFamily: Fonts.JUA,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  attemptedButton: {
    backgroundColor: Colors.success,
  },
  attemptedOutlineButton: {
    borderColor: Colors.success,
  },
  nextButton: {
    backgroundColor: '#FF6347',
    padding: 15,
    borderRadius: Radius.sm,
    alignItems: 'center',
    marginTop: Spacing.xs,
  },
  nextButtonDisabled: {
    backgroundColor: Colors.disabled,
  },
  nextButtonText: {
    color: Colors.surface,
    fontSize: Typography.bodyLarge,
    fontFamily: Fonts.JUA,
  },
});
